import "server-only";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import type { BeatInquiryInput, ContactMessageInput, InboundKind, InboundRecord, ProjectDiscoveryInput, SubmissionResult } from "./types";

const tables = { discoveries:"project_discoveries", messages:"contact_messages", "beat-inquiries":"beat_inquiries" } as const;
async function propertyId() { const db=createSupabaseAdminClient(); const {data,error}=await db.from("properties").select("id").eq("slug","jmt-music").single(); if(error||!data) throw new Error("property"); return {db,id:data.id as string}; }
async function insertIdempotent(table:string, token:string, row:Record<string,unknown>):Promise<SubmissionResult> { try { const {db,id}=await propertyId(); const existing=await db.from(table).select("id").eq("submission_token",token).maybeSingle(); if(existing.data) return {status:"success",id:existing.data.id,duplicate:true}; const result=await db.from(table).insert({property_id:id,submission_token:token,...row}).select("id").single(); if(result.error?.code==="23505"){const retry=await db.from(table).select("id").eq("submission_token",token).maybeSingle();if(retry.data)return {status:"success",id:retry.data.id,duplicate:true};} if(result.error||!result.data) return {status:"error",message:"Submission could not be saved."}; return {status:"success",id:result.data.id,duplicate:false}; } catch { return {status:"error",message:"Submission could not be saved."}; } }
const nil=(v?:string)=>v||null;
export function saveDiscovery(v:ProjectDiscoveryInput){return insertIdempotent(tables.discoveries,v.submissionToken,{first_name:v.firstName,artist_name:nil(v.artistName),has_artist_name:Boolean(v.artistName&&v.artistName!=="I don’t have one yet."),email:v.email,phone:nil(v.phone),project_type:v.projectType,vision:v.vision,inspiration:v.inspiration,current_stage:v.currentStage,timeline:v.timeline,additional_notes:nil(v.additionalNotes)});}
export function saveContactMessage(v:ContactMessageInput){return insertIdempotent(tables.messages,v.submissionToken,{name:v.name,email:v.email,phone:nil(v.phone),subject:nil(v.subject),message:v.message});}
export function saveBeatInquiry(v:BeatInquiryInput){return insertIdempotent(tables["beat-inquiries"],v.submissionToken,{name:v.name,artist_name:nil(v.artistName),email:v.email,phone:nil(v.phone),beat_slug:nil(v.beatSlug),beat_title:v.beatTitle,beat_url:nil(v.beatUrl),license_interest:nil(v.licenseInterest),intended_use:nil(v.intendedUse),message:v.message});}
export async function listInbound(kind:InboundKind,siteSlug:string):Promise<InboundRecord[]> { try { const db=createSupabaseAdminClient(); const p=await db.from("properties").select("id").eq("slug",siteSlug).maybeSingle(); if(!p.data)return[]; const result=await db.from(tables[kind]).select("*").eq("property_id",p.data.id).order("submitted_at",{ascending:false}); return (result.data||[]) as InboundRecord[]; } catch{return[];} }
export function inboundEnvironmentReady(){return Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY);}
export async function inboundCounts(siteSlug:string){const [d,m,b]=await Promise.all([listInbound("discoveries",siteSlug),listInbound("messages",siteSlug),listInbound("beat-inquiries",siteSlug)]);return {configured:inboundEnvironmentReady(),discoveries:d.filter(x=>x.status==="new").length,messages:m.filter(x=>x.status==="new").length,beatInquiries:b.filter(x=>x.status==="new").length,recent:[...d.map(x=>({...x,kind:"discoveries"})),...m.map(x=>({...x,kind:"messages"})),...b.map(x=>({...x,kind:"beat-inquiries"}))].filter(x=>x.status==="new").sort((a,b)=>String(b.submitted_at).localeCompare(String(a.submitted_at))).slice(0,6)};}
