import type { BeatInquiryInput, ContactMessageInput, ProjectDiscoveryInput } from "./types";
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const safeSlugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/i;
const clean = (value:unknown,max:number) => typeof value === "string" ? value.trim().slice(0,max) : "";
const optional = (value:unknown,max:number) => clean(value,max) || null;
function base(input:Record<string,unknown>) { const token=clean(input.submissionToken,36); const email=clean(input.email,254).toLowerCase(); if(!uuidPattern.test(token)||!emailPattern.test(email)) throw new Error("invalid"); return {token,email}; }
export function validateDiscovery(raw:unknown) { const input=(raw||{}) as Record<string,unknown>; const {token,email}=base(input); const value:ProjectDiscoveryInput={submissionToken:token,firstName:clean(input.firstName,160),artistName:clean(input.artistName,160),email,phone:clean(input.phone,40),projectType:clean(input.projectType,100),vision:clean(input.vision,8000),inspiration:clean(input.inspiration,8000),currentStage:clean(input.currentStage,100),timeline:clean(input.timeline,100),additionalNotes:clean(input.additionalNotes,8000)}; if(!value.firstName||!value.projectType||!value.vision||!value.inspiration||!value.currentStage||!value.timeline) throw new Error("invalid"); return value; }
export function validateContact(raw:unknown) { const input=(raw||{}) as Record<string,unknown>; const {token,email}=base(input); const value:ContactMessageInput={submissionToken:token,name:clean(input.name,160),email,phone:clean(input.phone,40),subject:clean(input.subject,200),message:clean(input.message,8000)}; if(!value.name||!value.message) throw new Error("invalid"); return value; }
export function validateBeatInquiry(raw:unknown) { const input=(raw||{}) as Record<string,unknown>; const {token,email}=base(input); const value:BeatInquiryInput={submissionToken:token,name:clean(input.name,160),artistName:clean(input.artistName,160),email,phone:clean(input.phone,40),beatSlug:clean(input.beatSlug,160),beatTitle:clean(input.beatTitle,200),beatUrl:clean(input.beatUrl,500),licenseInterest:clean(input.licenseInterest,160),intendedUse:clean(input.intendedUse,1000),message:clean(input.message,8000)}; if(!value.name||!value.beatTitle||!value.message) throw new Error("invalid"); if(value.beatSlug&&!safeSlugPattern.test(value.beatSlug)) value.beatSlug=""; if(value.beatUrl){try{const url=new URL(value.beatUrl);if(!["http:","https:"].includes(url.protocol))value.beatUrl="";}catch{value.beatUrl="";}} return value; }
export { optional };
